version: '3.8'

services:
  # Backend Service (Node.js API)
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - ./backend:/app # Mounts local backend code into container
      - /app/node_modules # Excludes local node_modules from overriding container's

  # Frontend Service (React App)
  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Database Service (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: